"""Recency weighting: off by default, exact in its limits, and aimed at Power only."""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from mri.ratings import backtest, mri2

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE = ROOT / "data" / "parquet" / "archive_games.parquet"
GOLDEN = Path(__file__).with_name("data") / "mri2_default_golden.json"

needs_archive = pytest.mark.skipif(not ARCHIVE.exists(), reason="archive not built")


@pytest.fixture(scope="module")
def season_2005() -> pd.DataFrame:
    return pd.read_parquet(ARCHIVE).query("season == 2005").reset_index(drop=True)


@needs_archive
def test_default_path_reproduces_the_pre_recency_solver(season_2005: pd.DataFrame) -> None:
    """Golden values were generated by the solver as it stood before weighting existed."""
    gold = json.loads(GOLDEN.read_text())
    model = mri2.fit(season_2005.iloc[:400], ridge=9.0, compression=28.0)
    for team, value in gold["power"].items():
        assert model.power[team] == pytest.approx(value, abs=1e-8)
        assert model.resume[team] == pytest.approx(gold["resume"][team], abs=1e-8)
    assert model.home_field == pytest.approx(gold["home_field"], abs=1e-8)
    assert model.sigma == pytest.approx(gold["sigma"], abs=1e-8)


@needs_archive
def test_none_and_omitted_are_the_same_fit(season_2005: pd.DataFrame) -> None:
    a = mri2.fit(season_2005.iloc[:400])
    b = mri2.fit(season_2005.iloc[:400], recency_half_life=None, season_games=len(season_2005))
    assert a.power.equals(b.power) and a.resume.equals(b.resume)
    assert (a.home_field, a.sigma) == (b.home_field, b.sigma)


@needs_archive
def test_flat_weights_reduce_to_the_unweighted_solve(season_2005: pd.DataFrame) -> None:
    plain = mri2.fit(season_2005.iloc[:400], with_efficiency=False)
    flat = mri2.fit(season_2005.iloc[:400], with_efficiency=False, recency_half_life=1e12)
    np.testing.assert_allclose(flat.power, plain.power, atol=1e-6)
    assert flat.home_field == pytest.approx(plain.home_field, abs=1e-6)
    assert flat.sigma == pytest.approx(plain.sigma, abs=1e-6)


def test_weight_shape_and_half_life_meaning() -> None:
    w = mri2.recency_weights(100, 0.25, season_games=100)
    assert w[-1] == 1.0 and (np.diff(w) > 0).all()
    # 25 games back is a quarter of a 100-game season: exactly one half-life.
    assert w[-1 - 25] == pytest.approx(0.5)
    # A slice of a longer season ages by the *season's* length, not its own.
    assert mri2.recency_weights(50, 0.25, season_games=100)[-1 - 25] == pytest.approx(0.5)
    with pytest.raises(ValueError):
        mri2.recency_weights(10, 0.0)


@needs_archive
def test_resume_ignores_recency(season_2005: pd.DataFrame) -> None:
    plain = mri2.fit(season_2005, with_efficiency=False)
    weighted = mri2.fit(season_2005, with_efficiency=False, recency_half_life=0.25)
    assert weighted.resume.equals(plain.resume)
    assert not weighted.power.equals(plain.power)


def test_recent_form_outweighs_old_form() -> None:
    """A team that lost its first half and won its second reads higher when recent games count more."""
    rows = []
    teams = ["A", "B", "C", "D"]
    for rnd in range(12):
        early = rnd < 6
        for home, away in (("B", "A"), ("D", "C")):
            # B hosts A and wins early, loses late; D hosts C by a steady 3.
            margin = (14 if early else -14) if home == "B" else 3
            rows.append({"team1": away, "team2": home, "pts1": 20.0, "pts2": 20.0 + margin,
                         "win1": float(margin < 0), "win2": float(margin > 0)})
        rows.append({"team1": teams[rnd % 2], "team2": teams[2 + rnd % 2], "pts1": 21.0, "pts2": 24.0,
                     "win1": 0.0, "win2": 1.0})
    games = pd.DataFrame(rows)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        plain = mri2.fit(games, ridge=1.0, with_efficiency=False, with_resume=False)
        recent = mri2.fit(games, ridge=1.0, with_efficiency=False, with_resume=False,
                          recency_half_life=0.2)
    assert recent.power["A"] - recent.power["B"] > plain.power["A"] - plain.power["B"]


@needs_archive
def test_walk_forward_passes_the_half_life_through_the_whole_chain() -> None:
    games = pd.read_parquet(ARCHIVE).query("season in (2005, 2006)")
    base = backtest.evaluate_archive(games, with_classic=False, seasons=[2006])
    same = backtest.evaluate_archive(games, with_classic=False, seasons=[2006], recency_half_life=None)
    weighted = backtest.evaluate_archive(games, with_classic=False, seasons=[2006], recency_half_life=0.3)
    pd.testing.assert_frame_equal(base, same)
    assert not np.allclose(base["mri2_mae"], weighted["mri2_mae"])
