"""Write a season out as an Excel workbook in the shape of the originals.

The point is an archive that behaves like the thing it replaces. Ben's
2003-2019 workbooks were live: Games held the raw results, Team Data
aggregated them with SUMIF, and the MRI column was a formula over those
aggregates, so correcting a score re-rated the season. Exporting a dead table
of numbers would lose that.

So the Classic half is rebuilt with its real formulas - the same SUMIF web, the
same named ranges, the same +/-35 game-credit expression - and recalculates on
edit exactly as it used to.

MRI 2.0 cannot be expressed that way. It solves every game simultaneously as a
regularized least-squares system, which a spreadsheet cannot represent, so it
is written as values with a sheet saying plainly that it is a snapshot. Better
an honest snapshot beside a live sheet than a formula that pretends.

Column layout matches the original workbooks exactly, so an old workbook and a
new one sit side by side without translation.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.workbook.defined_name import DefinedName

from ..ingest import registry
from ..ratings import classic

FONT = "Arial"
HEADER_FILL = PatternFill("solid", fgColor="D9D9D9")
NOTE_FILL = PatternFill("solid", fgColor="FFF2CC")

GAMES_HEADERS = [
    "Team1", "Team2", "Pnt1", "Pnt2", "Rush1", "Rush2", "Pass1", "Pass2",
    "TO1", "TO2", "WT1", "WT2",
    "T1W", "T1L", "T2W", "T2L", "T1OW", "T1OL", "T2OW", "T2OL", "T1Point", "T2Point",
]

TEAM_HEADERS = [
    "Team", "W", "L", "Opp W", "Opp L", "O2 W", "O2 L", "Pnts", "Rush", "RPG",
    "Orush", "Pass", "PPG", "Opass", "TO's", "O TO's", "", "Def/G", "TO Diff",
    "SOS", "SOS Rank", "MRI",
]


def _style_header(sheet, row: int, count: int) -> None:
    for column in range(1, count + 1):
        cell = sheet.cell(row, column)
        cell.font = Font(name=FONT, bold=True, size=10)
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center")


def write_season(
    year: int,
    games: pd.DataFrame,
    modern: pd.DataFrame | None,
    path: Path,
) -> Path:
    """Build one season's workbook.

    ``games`` must carry the archive column names and have non-FBS opponents
    already pooled into "Non D1A", which is what MRI Classic expects.
    """
    teams = sorted({t for t in set(games["team1"]) | set(games["team2"])
                    if t != classic.POOLED_FCS})
    ordered = teams + [classic.POOLED_FCS]

    book = Workbook()
    book.remove(book.active)

    _about_sheet(book, year, len(games), len(teams))
    _games_sheet(book, games, len(ordered))
    stats_row = _team_data_sheet(book, games, ordered)
    _mri_sheet(book, ordered, len(games))
    if modern is not None and not modern.empty:
        _modern_sheet(book, modern)

    _define_names(book, stats_row)

    path.parent.mkdir(parents=True, exist_ok=True)
    book.save(path)
    return path


def _about_sheet(book: Workbook, year: int, game_count: int, team_count: int) -> None:
    sheet = book.create_sheet("About")
    lines = [
        (f"MRI {year}", True),
        ("", False),
        (f"{game_count} games, {team_count} FBS teams.", False),
        ("", False),
        ("WHAT IS LIVE", True),
        ("Games, Team Data and MRI carry the original formulas. Correct a score on", False),
        ("the Games sheet and the whole season re-rates, exactly as the 2003-2019", False),
        ("workbooks did. Only columns A-L of Games are data; M onward are formulas.", False),
        ("", False),
        ("WHAT IS A SNAPSHOT", True),
        ("The MRI 2.0 sheet is values, not formulas. That rating solves every game", False),
        ("in the season at once as a regularized least-squares system, which a", False),
        ("spreadsheet cannot express. Editing a score will not update it; rerun", False),
        ("scripts/export_workbooks.py instead.", False),
        ("", False),
        ("NON-FBS OPPONENTS", True),
        ('Pooled into a single "Non D1A" team, as in the originals. MRI 2.0 rates', False),
        ("them individually, which is one reason the two ratings disagree.", False),
        ("", False),
        ("Generated by github.com/bmiraski/mri_ratings", False),
    ]
    for index, (text, bold) in enumerate(lines, start=1):
        cell = sheet.cell(index, 1, text)
        cell.font = Font(name=FONT, bold=bold, size=13 if index == 1 else 10)
    sheet.column_dimensions["A"].width = 78
    sheet.cell(5, 1).fill = NOTE_FILL
    sheet.cell(11, 1).fill = NOTE_FILL


def _games_sheet(book: Workbook, games: pd.DataFrame, team_rows: int) -> None:
    sheet = book.create_sheet("Games")
    sheet.append(GAMES_HEADERS)
    _style_header(sheet, 1, len(GAMES_HEADERS))

    last = team_rows + 1  # Team Data lookup range ends here
    for offset, row in enumerate(games.itertuples(), start=2):
        sheet.cell(offset, 1, row.team1)
        sheet.cell(offset, 2, row.team2)
        for column, value in enumerate(
            [row.pts1, row.pts2, row.rush1, row.rush2, row.pass1, row.pass2,
             row.to1, row.to2, row.win1, row.win2],
            start=3,
        ):
            sheet.cell(offset, column, float(value) if pd.notna(value) else 0.0)

        r = offset
        table = f"'Team Data'!$A$1:$P${last}"
        # Opponent records, looked up the way the originals did.
        sheet.cell(r, 13, f"=VLOOKUP(A{r},{table},2,FALSE)")
        sheet.cell(r, 14, f"=VLOOKUP(A{r},{table},3,FALSE)")
        sheet.cell(r, 15, f"=VLOOKUP(B{r},{table},2,FALSE)")
        sheet.cell(r, 16, f"=VLOOKUP(B{r},{table},3,FALSE)")
        sheet.cell(r, 17, f"=VLOOKUP(A{r},{table},4,FALSE)")
        sheet.cell(r, 18, f"=VLOOKUP(A{r},{table},5,FALSE)")
        sheet.cell(r, 19, f"=VLOOKUP(B{r},{table},4,FALSE)")
        sheet.cell(r, 20, f"=VLOOKUP(B{r},{table},5,FALSE)")
        # Game credit: capped margin weighted by how good the opponent was.
        sheet.cell(r, 21, (
            f"=IF(K{r}=1,(MIN(35,(C{r}-D{r})))*(O{r}/(O{r}+P{r}))*(S{r}/(S{r}+T{r})),"
            f"(MAX(-35,(C{r}-D{r})))*(IF(P{r}=0,0.1,(P{r}/(O{r}+P{r}))))*(T{r}/(S{r}+T{r})))"
        ))
        sheet.cell(r, 22, (
            f"=IF(L{r}=1,(MIN(35,(D{r}-C{r})))*(M{r}/(M{r}+N{r}))*(Q{r}/(Q{r}+R{r})),"
            f"(MAX(-35,(D{r}-C{r})))*(IF(N{r}=0,0.1,(N{r}/(M{r}+N{r}))))*(R{r}/(R{r}+Q{r})))"
        ))

    for column in range(1, len(GAMES_HEADERS) + 1):
        sheet.column_dimensions[get_column_letter(column)].width = 18 if column < 3 else 9
    sheet.freeze_panes = "C2"


def _team_data_sheet(book: Workbook, games: pd.DataFrame, ordered: list[str]) -> int:
    sheet = book.create_sheet("Team Data")
    sheet.append(TEAM_HEADERS)
    _style_header(sheet, 1, len(TEAM_HEADERS))

    n = len(games)
    g = f"Games!$A$2:$A${n + 1}"
    h = f"Games!$B$2:$B${n + 1}"

    def both(column: str, away_column: str) -> str:
        """SUMIF over both sides of the game log, as the originals did."""
        return (f"SUMIF({g},$A{{r}},Games!{column}$2:{column}${n + 1})"
                f"+SUMIF({h},$A{{r}},Games!{away_column}$2:{away_column}${n + 1})")

    last_team_row = len(ordered) + 1
    fbs_last = len(ordered)  # the pooled row sits last and is excluded from stats

    for offset, team in enumerate(ordered, start=2):
        r = offset
        pooled = team == classic.POOLED_FCS
        sheet.cell(r, 1, team)
        sheet.cell(r, 2, "=" + both("$K", "$L").format(r=r))
        sheet.cell(r, 3, "=" + both("$L", "$K").format(r=r))
        sheet.cell(r, 4, "=" + both("$O", "$M").format(r=r))
        sheet.cell(r, 5, "=" + both("$P", "$N").format(r=r))
        sheet.cell(r, 6, "=" + both("$S", "$Q").format(r=r))
        sheet.cell(r, 7, "=" + both("$T", "$R").format(r=r))
        sheet.cell(r, 8, "=" + both("$U", "$V").format(r=r))
        sheet.cell(r, 9, "=" + both("$E", "$F").format(r=r))
        if not pooled:
            sheet.cell(r, 10, f"=IFERROR(I{r}/(B{r}+C{r}),0)")
        sheet.cell(r, 11, "=" + both("$F", "$E").format(r=r))
        sheet.cell(r, 12, "=" + both("$G", "$H").format(r=r))
        if not pooled:
            sheet.cell(r, 13, f"=IFERROR(L{r}/(B{r}+C{r}),0)")
        sheet.cell(r, 14, "=" + both("$H", "$G").format(r=r))
        sheet.cell(r, 15, "=" + both("$I", "$J").format(r=r))
        sheet.cell(r, 16, "=" + both("$J", "$I").format(r=r))
        # The pooled row exists only so opponent lookups resolve. It gets no
        # per-game rates, no rank and no rating - exactly as in the originals,
        # where ranking it against a range it is excluded from yielded #N/A.
        if pooled:
            continue
        sheet.cell(r, 18, f"=IFERROR((K{r}+N{r})/(B{r}+C{r}),0)")
        sheet.cell(r, 19, f"=P{r}-O{r}")
        sheet.cell(r, 20, f"=IFERROR((D{r}/(D{r}+E{r}))*(F{r}/(F{r}+G{r})),0)")
        sheet.cell(r, 21, f"=RANK(T{r},T$2:T${fbs_last})")
        sheet.cell(r, 22, (
            f"=IFERROR((B{r}/(B{r}+C{r}))*25,0)+IFERROR((D{r}/(D{r}+E{r}))*25,0)"
            f"+IFERROR((F{r}/(F{r}+G{r}))*10,0)+H{r}"
            f"+((J{r}-RMEAN)/RDEV)*5+((M{r}-PMEAN)/PDEV)*5"
            f"+((DMEAN-R{r})/DDEV)*7+((S{r}-TOMEAN)/TODEV)*3"
        ))

    stats_row = last_team_row + 1
    sheet.cell(stats_row, 1, "Mean").font = Font(name=FONT, bold=True, size=10)
    sheet.cell(stats_row + 1, 1, "StDev").font = Font(name=FONT, bold=True, size=10)
    for column in (10, 13, 18, 19):
        letter = get_column_letter(column)
        sheet.cell(stats_row, column, f"=AVERAGE({letter}2:{letter}{fbs_last})")
        sheet.cell(stats_row + 1, column, f"=STDEV({letter}2:{letter}{fbs_last})")

    note = sheet.cell(stats_row + 3, 1,
                      "Mean and StDev cover FBS teams only; the pooled Non D1A row is excluded, "
                      "as in the original workbooks.")
    note.font = Font(name=FONT, italic=True, size=9)

    sheet.column_dimensions["A"].width = 24
    for column in range(2, len(TEAM_HEADERS) + 1):
        sheet.column_dimensions[get_column_letter(column)].width = 10
    sheet.freeze_panes = "B2"
    return stats_row


def _mri_sheet(book: Workbook, ordered: list[str], game_count: int) -> None:
    sheet = book.create_sheet("MRI", 0)
    sheet.append(["Rank", "Team", "W", "L", "MRI Raw", "Avg."])
    _style_header(sheet, 1, 6)

    fbs = [t for t in ordered if t != classic.POOLED_FCS]
    last = len(ordered) + 1
    table = f"'Team Data'!$A$2:$V${last}"

    for offset, team in enumerate(fbs, start=2):
        r = offset
        sheet.cell(r, 1, f"=RANK(E{r},E$2:E${len(fbs) + 1})")
        sheet.cell(r, 2, team)
        sheet.cell(r, 3, f"=VLOOKUP(B{r},{table},2,FALSE)")
        sheet.cell(r, 4, f"=VLOOKUP(B{r},{table},3,FALSE)")
        sheet.cell(r, 5, f"=VLOOKUP(B{r},{table},22,FALSE)")
        sheet.cell(r, 6, f"=IFERROR(E{r}/(C{r}+D{r}),0)")
        sheet.cell(r, 5).number_format = "0.000"
        sheet.cell(r, 6).number_format = "0.000"

    sheet.column_dimensions["B"].width = 24
    for column in ("A", "C", "D", "E", "F"):
        sheet.column_dimensions[column].width = 11
    sheet.freeze_panes = "A2"


def _modern_sheet(book: Workbook, modern: pd.DataFrame) -> None:
    sheet = book.create_sheet("MRI 2.0", 1)
    sheet.append(["Rank", "Team", "Conference", "Power", "Resume", "Resume Rank", "Games"])
    _style_header(sheet, 1, 7)

    for offset, row in enumerate(modern.itertuples(), start=2):
        sheet.cell(offset, 1, int(row.rank))
        sheet.cell(offset, 2, row.team)
        sheet.cell(offset, 3, registry.conference_of(row.team) or "")
        sheet.cell(offset, 4, round(float(row.power), 2)).number_format = "+0.00;-0.00"
        if pd.notna(row.resume):
            sheet.cell(offset, 5, round(float(row.resume), 2)).number_format = "+0.00;-0.00"
            sheet.cell(offset, 6, int(row.resume_rank))
        sheet.cell(offset, 7, int(row.games))

    note = sheet.cell(len(modern) + 3, 1,
                      "Snapshot, not formulas: MRI 2.0 solves the whole season at once as a "
                      "regularized least-squares system, which a spreadsheet cannot express. "
                      "Power is points against an average FBS team; Resume is wins above what "
                      "an average team would manage against the same schedule.")
    note.font = Font(name=FONT, italic=True, size=9)
    note.fill = NOTE_FILL

    sheet.column_dimensions["B"].width = 24
    sheet.column_dimensions["C"].width = 18
    for column in ("A", "D", "E", "F", "G"):
        sheet.column_dimensions[column].width = 12
    sheet.freeze_panes = "A2"


def _define_names(book: Workbook, stats_row: int) -> None:
    """The named ranges the MRI formula reads, as in the originals."""
    names = {
        "RMEAN": f"J${stats_row}", "RDEV": f"J${stats_row + 1}",
        "PMEAN": f"M${stats_row}", "PDEV": f"M${stats_row + 1}",
        "DMEAN": f"R${stats_row}", "DDEV": f"R${stats_row + 1}",
        "TOMEAN": f"S${stats_row}", "TODEV": f"S${stats_row + 1}",
    }
    for name, reference in names.items():
        book.defined_names[name] = DefinedName(name, attr_text=f"'Team Data'!${reference}")
